### ISSUE TITLE
Sandbox scripts import nengo_loihi.NumpySimulator

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-loihi#107]
The scripts:
 - `sandbox/v_node_ens.py`
 - `sandbox/pes_learning_snips.py`

try to import `nengo_loihi.NumpySimulator` which doesn't exist.

Both scripts also don't work for me, because there's a subfolder named [`nxsdk`](https://github.com/nengo/nengo-loihi/tree/da7be192e2bed7f1bac8a90f117a6319eca0c041/sandbox/nxsdk) which I can import from that subdirectory, and so it thinks my laptop has the `LoihiSimulator` -- even though it doesn't!

```
Running on Loihi
Traceback (most recent call last):
  File "v_node_ens.py", line 29, in <module>
    with Simulator(model, precompute=True) as sim:
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/simulator.py", line 243, in __init__
    self.loihi = self.model.get_loihi(seed=seed)
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/loihi_cx.py", line 470, in get_loihi
    return LoihiSimulator(self, seed=seed)
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/loihi_interface.py", line 389, in __init__
    self.check_nxsdk_version()
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/loihi_interface.py", line 422, in check_nxsdk_version
    nxsdk()
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/loihi_interface.py", line 26, in no_nxsdk
    raise exc_info[1]
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/loihi_interface.py", line 17, in <module>
    from nxsdk.arch.n2a.compiler.tracecfggen.tracecfggen import TraceCfgGen
ModuleNotFoundError: No module named 'nxsdk.arch'
```

I'm guessing this whole directory is somewhat deprecated?

**Comment by drasmuss** [comment]
Yeah the whole `sandbox` directory has no guarantees of working or being up to date. Perhaps we should add a README to that effect in the folder so no one is confused. Or we could probably just get rid of that directory entirely now that we're moving into a more stable development cycle.  The `examples` directory is the place to find working examples.

**Comment by tbekolay** [comment]
Yeah I had sort of planned to convert any useful sandbox examples to tests and get rid of the rest. Made #18 to track that, but other stuff is more pressing atm.

**Comment by arvoelke** [comment]
Ah, missed that one. I'll close this in favour of #18. Thanks!
