### ISSUE TITLE
Input nodes cannot be sliced

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#16]
As reported by @tcstewar:

```python
import nengo
model = nengo.Network()
with model:
    stim = nengo.Node([0,0])
    a = nengo.Ensemble(n_neurons=60, dimensions=3)
    nengo.Connection(stim, a[:2])

import nengo_loihi
with nengo_loihi.Simulator(model, precompute=True) as sim:
    sim.run(0.1)
```

On loihi, this fails as follows:

```
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_cx.py", line 370, in get_loihi
    return LoihiSimulator(self, seed=seed)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 361, in __init__
    self.build(cx_model, seed=seed)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 378, in build
    self.n2board = build_board(self.board)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 30, in build_board
    build_chip(n2chip, chip)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 38, in build_chip
    build_core(n2core, core)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 197, in build_core
    build_input(n2core, core, inp, cx_idxs)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 242, in build_input
    build_axons(n2core, core, spike_input, axon, cx_idxs)
  File "/home/kate/nengo-loihi/nengo_loihi/loihi_interface.py", line 326, in build_axons
    assert axons.n_axons == len(cx_idxs) == len(taxon_idxs)
AssertionError
```

In the simulator, it fails like this:

```
Traceback (most recent call last):
  File ".\dim_fail.py", line 12, in <module>
    sim.run(0.1)
  File "c:\users\terry\documents\github\nengo-loihi\nengo_loihi\simulator.py", line 314, in run
    self.run_steps(steps)
  File "c:\users\terry\documents\github\nengo-loihi\nengo_loihi\simulator.py", line 338, in run_steps
    self.simulator.step()
  File "c:\users\terry\documents\github\nengo-loihi\nengo_loihi\loihi_cx.py", line 517, in step
    self.a_in[synapses] += input.spikes[self.t]
ValueError: operands could not be broadcast together with shapes (6,) (4,) (6,)
```

**Comment by drasmuss** [comment]
Not sure when exactly this was fixed, but tested on emulator and hardware and both are working now.
