### ISSUE TITLE
Adding a neuron probe with a synapse results in build error

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-loihi#182]
Minimal example:
```
import nengo
import nengo_loihi

with nengo.Network() as net:
    a = nengo.Ensemble(10, 1)
    p = nengo.Probe(a.neurons, synapse=0.1)

with nengo_loihi.Simulator(net) as sim:
    pass
```
Traceback:
```
Traceback (most recent call last):
  File "...\tmp.py", line 8, in <module>
    with nengo_loihi.Simulator(net) as sim:
  File "...\nengo_loihi\simulator.py", line 364, in __init__
    self.sims["emulator"] = EmulatorInterface(self.model, seed=seed)
  File "...\nengo_loihi\emulator\interface.py", line 62, in __init__
    self.probes = ProbeState(self.block_info, self.inputs, model.dt)
  File "...\nengo_loihi\emulator\interface.py", line 619, in __init__
    else probe.weights.shape[1])
AttributeError: 'float' object has no attribute 'shape'
```

**Comment by drasmuss** [comment]
Fixed in #183
