### ISSUE TITLE
Scipy sparse import error

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo-loihi#252]
I encountered this issue with the current master branch of `nengo-loihi`, `nxsdk 0.8.5.1`, and with the `nengolib` repo installed in a python environment. The error occurs trying to run `ens_ens.py` from the `docs/examples` folder.

```
Traceback (most recent call last):
  File "ens_ens.py", line 35, in <module>
    with nengo_loihi.Simulator(model) as sim:
  File "/home-mjc/pawel/nengo-loihi/nengo_loihi/simulator.py", line 146, in __init__
    self.model.build(network)
  File "/home-mjc/pawel/nengo-loihi/nengo_loihi/builder/builder.py", line 208, in build
    built = model.builder.build(model, obj, *args, **kwargs)
  File "/home/pawel/anaconda3/envs/loihi-mjc/lib/python3.5/site-packages/nengo/builder/builder.py", line 218, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home/pawel/anaconda3/envs/loihi-mjc/lib/python3.5/site-packages/nengo/builder/network.py", line 113, in build_network
    model.build(conn)
  File "/home-mjc/pawel/nengo-loihi/nengo_loihi/builder/builder.py", line 208, in build
    built = model.builder.build(model, obj, *args, **kwargs)
  File "/home/pawel/anaconda3/envs/loihi-mjc/lib/python3.5/site-packages/nengo/builder/builder.py", line 218, in build
    return cls.builders[obj_cls](model, obj, *args, **kwargs)
  File "/home-mjc/pawel/nengo-loihi/nengo_loihi/builder/connection.py", line 60, in build_connection
    build_chip_connection(model, conn)
  File "/home-mjc/pawel/nengo-loihi/nengo_loihi/builder/connection.py", line 467, in build_chip_connection
    if isinstance(transform, scipy.sparse.spmatrix):
AttributeError: module 'scipy' has no attribute 'sparse'
```

I fixed it locally by doing `import scipy.sparse` in `builder/connections.py`, right after the `import scipy` line.

**Comment by hunse** [comment]
I just ran into this when testing on a fresh install with Nengo 2.8.0. I've put a fix in #234.
